### ISSUE TITLE
CatapushAuthenticationError{reason='Communication error', status='500'}

### ISSUE THREAD

**Issue by manawaraquevix** [Catapush/catapush-android-sdk-example#1]
Hi,
I am trying your sample app. I have changed applicationId of sample and added credentials. While I run sample on my device it gives me following error-------

CatapushAuthenticationError{reason='Communication error', status='500'}

**Comment by hamen** [comment]
Hi. Could you please send a mail to info@catapush.com with your appId and your credentials, please?

**Comment by manawaraquevix** [comment]
Hi,
Thanks for quick response. I have sent an email with appId and credentials.

**Comment by manawaraquevix** [comment]
03-28 12:28:13.074 23176-23176/com.catapush.myf.app D/MyApp: Catapush has been initialized
03-28 12:28:13.092 23176-23176/com.catapush.myf.app V/ActivityThread: ActivityRecord{3b0373e2 token=android.os.BinderProxy@30936373 {com.catapush.myf.app/com.catapush.example.app.MainActivity}}: app=com.catapush.example.app.MyApplication@1355dfe7, appName=com.catapush.myf.app, pkg=com.catapush.myf.app, comp={com.catapush.myf.app/com.catapush.example.app.MainActivity}, dir=/data/app/com.catapush.myf.app-1/base.apk
03-28 12:28:15.745 23176-23176/com.catapush.myf.app E/MyApp: Error Message: Communication error
03-28 12:28:15.747 23176-23176/com.catapush.myf.app E/MyApp: Error Message: Communication error
